package com.izmo.core.model;

// Generated Dec 12, 2015 1:00:05 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FormsId generated by hbm2java
 */
@Embeddable
public class FormsId implements java.io.Serializable {

	private int formId;
	private int fkLocaleId;

	public FormsId() {
	}

	public FormsId(int formId, int fkLocaleId) {
		this.formId = formId;
		this.fkLocaleId = fkLocaleId;
	}

	@Column(name = "form_id", nullable = false)
	public int getFormId() {
		return this.formId;
	}

	public void setFormId(int formId) {
		this.formId = formId;
	}

	@Column(name = "fk_locale_id", nullable = false)
	public int getFkLocaleId() {
		return this.fkLocaleId;
	}

	public void setFkLocaleId(int fkLocaleId) {
		this.fkLocaleId = fkLocaleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FormsId))
			return false;
		FormsId castOther = (FormsId) other;

		return (this.getFormId() == castOther.getFormId())
				&& (this.getFkLocaleId() == castOther.getFkLocaleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFormId();
		result = 37 * result + this.getFkLocaleId();
		return result;
	}

}
