package com.izmo.core.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Forms generated by hbm2java
 */
@Entity
@Table(name = "forms")
public class Forms implements java.io.Serializable {

	private FormsId id;
	private String formName;
	private String level;
	private String pageType;
	private String thankYouPageUrl;

	public Forms() {
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "formId", column = @Column(name = "form_id", nullable = false)),
			@AttributeOverride(name = "fkLocaleId", column = @Column(name = "fk_locale_id", nullable = false)) })
	public FormsId getId() {
		return this.id;
	}

	public void setId(FormsId id) {
		this.id = id;
	}

	@Column(name = "form_name", nullable = false, length = 100)
	public String getFormName() {
		return this.formName;
	}

	public void setFormName(String formName) {
		this.formName = formName;
	}

	@Column(name = "level", nullable = false, length = 4)
	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	@Column(name = "thank_you_page_url", nullable = false, length = 150)
	public String getThankYouPageUrl() {
		return this.thankYouPageUrl;
	}

	public void setThankYouPageUrl(String thankYouPageUrl) {
		this.thankYouPageUrl = thankYouPageUrl;
	}

	@Column(name = "page_type", length = 6)
	public String getPageType() {
		return pageType;
	}

	public void setPageType(String pageType) {
		this.pageType = pageType;
	}

}
